[package]
name = "arns"
version = "0.1.0"
description = "Problem of FFRI × NFLabs. Cybersecurity Challenge 2025"
edition = "2024"
publish = false

[dependencies]

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
strip = true
