---

- name: ユーザーを追加
  win_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: present
  with_items: "{{ win_ctf_users }}"

- name: リモートデスクトップグループに追加
  win_group_membership:
    name: "Remote Desktop Users"
    members: "{{ item.name }}"
    state: present
  with_items: "{{ win_ctf_users }}"

- name: IIS のインストール
  win_feature:
    name: Web-Server
    state: present
    include_management_tools: yes

- name: Webサイト用ファイルのコピー
  win_copy:
    src: files/website
    dest: C:\inetpub\wwwroot\

- name: Web サイトの作成
  win_iis_website:
    name: "Mirai IT Systems Web Site"
    state: started
    hostname : "www.mirai-itsystems.local"
    port: 80
    physical_path: 'C:\inetpub\wwwroot\website'

- name: 環境変数の設定
  win_environment:
    name: PATH
    value: 'C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Monitor\dll\MailNotifier;'
    state: present
    level: machine

- name: IIS管理プログラムをコピー
  win_copy:
    src: files/Monitor
    dest: C:\

- name: C:\Monitorにユーザーの書き込み権限を追加
  win_acl:
    path: C:\Monitor
    user: Users
    rights: write, read, ReadAndExecute, ListDirectory
    type: allow
    state: present
    inherit: None
    propagation: none

- name: .NET Framework 4.8 のインストーラーをコピー
  win_copy:
    src: files/dotnet-runtime-8.0.18-win-x64.exe
    dest: C:\Users\Administrator\Desktop
    mode: "0755"

- name: .NET Framework 4.8 のインストール
  win_command: C:\Users\Administrator\Desktop\dotnet-runtime-8.0.18-win-x64.exe /install /quiet /norestart

- name: MonitorIISタスクの作成（ログオン状態に関係なく、1分ごとに繰り返し実行）
  win_scheduled_task:
    name: "MonitorIIS"
    description: "IIS監視タスク"
    actions:
      - path: C:\MONITOR\MonitorIISTask.exe
    triggers:
      - type: daily
        start_boundary: '2024-01-01T00:00:00'
        repetition:
          interval: PT1M
          duration: P1D
        enabled: true
    username: "Administrator"
    password: "{{ win_administrator_password }}"
    logon_type: password
    state: present
# ↑だけだとdevelop_commonからタスクが見えないので、以下のようにする
# - C:\Windows\System32\Tasks以下の読み込み権限の付与
# - 以下のPowershellの実行
# # 1. COM API に接続
# $service = New-Object -ComObject "Schedule.Service"
# $service.Connect()
#
# 2. タスクの参照を取得（ルートフォルダにある前提）
# $folder = $service.GetFolder("\")
# $task = $folder.GetTask("MonitorIIS")
#
# 3. 現在のセキュリティ記述子を取得（SDDL 形式）
# $sd = $task.GetSecurityDescriptor(0)
#
# 4. SDDL 文字列として Users に読み取り権を追加
#    D:(A;;FR;;;BU) = Allow Read for Built-in Users
# $updatedSddl = "D:(A;;FR;;;BU)" + $sd
#
# 5. 修正した SDDL をタスクに反映
# $task.SetSecurityDescriptor($updatedSddl, 0)

