---

# 必要スペック
# インスタンス: t3.medium
# ストレージ: 30GB
# 所要時間: 約5分

# m.yamadaユーザを使用

- name: systemd-resolveを停止
  systemd:
    name: systemd-resolved
    state: stopped
  become: true

- name: systemd-resolveを無効化
  systemd:
    name: systemd-resolved
    enabled: false
  become: true

- name: 配信用の hosts-dnsmasq ファイルを配置
  template:
    src: hosts-dnsmasq.j2
    dest: /etc/hosts-dnsmasq
    owner: root
    group: root
    mode: '0644'
  become: true

- name: dnsmasq を設定
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: dnsmasq を再起動
  service:
    name: dnsmasq
    state: restarted
    enabled: true
  become: true

- name: 端末を再起動
  reboot:
    msg: "Rebooting the system to apply changes"
    connect_timeout: 5
    reboot_timeout: 600
  become: true

- name: nginxの設定ファイルをコピー
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'
  become: true

- name: nginxを再起動
  service:
    name: nginx
    state: restarted
    enabled: true
  become: true

- name: gitlabのpumaの設定を変更
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^\\s*puma\\['worker_processes'\\]\\s*=.*"
    line: "puma['worker_processes'] = 0"
    backrefs: no
  become: true

- name: gitlabの設定を再構成
  command: gitlab-ctl reconfigure
  become: true
