---

# 実行前にやること
# main.yamlにgitlab_root_tokenを設定する

# 実行後にやること
# Adminによる認証を無効化

# 必要スペック
# AMI: Ubuntu Server 24.04 LTS
# アート: 64bit (x86)
# インスタンス: t3.large
# ストレージ: 30GB
# 所要時間: 約40分（AMI作成完了まで）

- name: swapfileが存在するか確認
  stat:
    path: /swapfile
  register: swapfile_stat

- name: swap領域を確保
  command: dd if=/dev/zero of=/swapfile bs=1M count=1024
  become: true
  when: not swapfile_stat.stat.exists

- name: swap領域が有効か確認
  command: swapon --show
  register: swap_status
  ignore_errors: true

- name: swap領域を作成
  block:
  - name: swap領域として設定
    command: mkswap /swapfile
  - name: swap領域を有効化
    command: swapon /swapfile
  become: true
  when: not swap_status.stdout

# 設定がなければエラーを出したうえで続行
- name: swapの永続化がされているかを確認
  shell: grep -q '/swapfile' /etc/fstab
  register: swap_fstab_check
  ignore_errors: true
  changed_when: false

- name: swap領域を永続化
  lineinfile:
    path: /etc/fstab
    line: '/swapfile none swap sw 0 0'
    state: present
  become: true
  when: swap_fstab_check.rc != 0

- name: open-ssh-server, postfix, python3-pipをインストール
  apt:
    update_cache: yes
    name:
      - openssh-server
      - postfix
      - python3-pip
    state: present
  become: true

- name: pipからpython-gitlabをインストール
  pip:
    name: python-gitlab
    state: present
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: "1"

- name: 再起動
  reboot:
    msg: "Rebooting the system to apply changes"
    connect_timeout: 5
    reboot_timeout: 600
  become: true

- name: curlからスクリプトを実行
  shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash
  become: true

- name: GitLabをインストール
  apt:
    name: gitlab-ee
    state: present
  become: true

- name: GitLabの設定ファイルをコピー
  copy:
    src: gitlab.rb
    dest: /etc/gitlab/gitlab.rb
    mode: "0644"
  become: yes

- name: 設定を変更
  command: gitlab-ctl reconfigure
  become: yes

- name: GitLabが302リダイレクトを返すまで待機
  command: curl --head --silent http://localhost:8480/
  register: gitlab_status
  until: gitlab_status.stdout.find("302 Found") != -1
  retries: 30
  delay: 10
  changed_when: false

- name: 初期化スクリプトのコピー
  copy:
    src: initial_configuration.sh
    dest: /opt/gitlab/initial_configuration.sh
    mode: "0755"
  become: yes

- name: initial_configuration.sh の実行
  command: /opt/gitlab/initial_configuration.sh
  become: yes

- name: GitLabのrootユーザーのトークンを発行
  shell: >
    gitlab-rails runner "user = User.find_by_username('root'); token = user.personal_access_tokens.create(scopes: [:api], name: 'Root API Token', expires_at: 365.days.from_now); token.set_token('{{ gitlab_root_token }}'); token.save!"
  ignore_errors: true
  become: yes

- name: GitLabの管理者としての設定を変更
  shell: >
    curl --request PUT \
    --header "PRIVATE-TOKEN: {{ gitlab_root_token }}" \
    --url 'http://localhost:8480/api/v4/application/settings?email_restrictions=&require_admin_approval_after_user_signup=false&after_sign_up_text=&gitaly_timeout_default=57&gitaly_timeout_medium=57&gitaly_timeout_fast=57'

- name: "GitLab: 'Mirai IT Systems'グループを作成"
  gitlab_group:
    api_url: "http://localhost:8480/"
    api_token: "{{ gitlab_root_token }}"
    name: "Mirai IT Systems"
    path: "mirai-it-systems"
    state: present
    visibility: public

- name: 'GitLab Mirai IT Systemsグループにメンバーを招待'
  community.general.gitlab_group_members:
    api_url: "http://localhost:8480/"
    api_token: "{{ gitlab_root_token }}"
    gitlab_group: "mirai-it-systems"
    gitlab_user: "{{ item }}"
    state: present
    access_level: developer
  with_items:
    - r.nomura
    - c.sakamoto
    - m.yamada
    - k.sayama

- name: "GitLab: 'www.mirai-itsystems.local'リポジトリを作成"
  gitlab_project:
    api_url: "http://localhost:8480/"
    api_token: "{{ gitlab_root_token }}"
    name: "www.mirai-itsystems.local"
    group: "mirai-it-systems"
    visibility: public
    state: present

- name: "GitLab: 'Internal'リポジトリを作成"
  gitlab_project:
    api_url: "http://localhost:8480/"
    api_token: "{{ gitlab_root_token }}"
    name: "Internal"
    group: "mirai-it-systems"
    visibility: private
    state: present

- name: "GitLabのリポジトリを作成するためのスクリプトをコピー"
  copy:
    src: files/gitlab.tar.gz
    dest: ~/
    mode: "0755"

- name: "GitLabのリポジトリを作成するためのスクリプトを解凍"
  unarchive:
    src: ~/gitlab.tar.gz
    dest: ~/
    mode: "0755"
    remote_src: yes
  
- name: "GitLab: 'www.mirai-itsystems.local'リポジトリを作成"
  command: ~/gitlab/repo/repo_create.sh ~/gitlab/repo/public/

- name: "GitLab: www.mirai-itsystems.localをリモートリポジトリに設定"
  command: git remote add origin http://r.nomura:CYnFUPZ8v%X8iWzs@localhost:8480/mirai-it-systems/www.mirai-itsystems.local.git
  args:
    chdir: ~/gitlab/repo/public/working_dir

- name: "GitLab: www.mirai-itsystems.localをプッシュ"
  command: git push --set-upstream origin --all
  args:
    chdir: ~/gitlab/repo/public/working_dir

- name: "GitLab: 'Internal'リポジトリを作成"
  command: ~/gitlab/repo/repo_create.sh ~/gitlab/repo/private/

- name: "GitLab: 'Internal'リポジトリをリモートリポジトリに設定"
  command: git remote add origin http://r.nomura:CYnFUPZ8v%X8iWzs@localhost:8480/mirai-it-systems/Internal.git
  args:
    chdir: ~/gitlab/repo/private/working_dir

- name: "GitLab: 'Internal'リポジトリをプッシュ"
  command: git push --set-upstream origin --all
  args:
    chdir: ~/gitlab/repo/private/working_dir

- name: "GitLab: Internalリポジトリにissueを作成"
  command: 
    cmd: ~/gitlab/issue/issue_create.sh http://localhost:8480/ 2 private/users.json private/issues.json {{ gitlab_root_token }}
    chdir: ~/gitlab/issue

- name: dnsmasqのインストール
  apt:
    name: dnsmasq
    state: present
  become: yes

- name: nginxをインストール
  apt:
    name: nginx
    state: present
  become: yes

- name: ユーザー m.yamada を追加
  user:
    name: m.yamada
    state: present
    shell: /bin/bash
  become: yes

- name: .sshディレクトリを作成
  file:
    path: /home/m.yamada/.ssh
    state: directory
    mode: "0700"
    owner: m.yamada
    group: m.yamada
  become: yes

- name: m.yamadaでSSHできるように鍵を追加
  copy:
    src: id_ed25519.pub
    dest: /home/m.yamada/.ssh/authorized_keys
    mode: "0600"
    owner: m.yamada
    group: m.yamada
  become: yes

- name: m.yamadaでSudoできるように設定
  community.general.sudoers:
    name: m-yamada
    user: m.yamada
    commands: ALL
    validation: required
  become: yes

- name: 再起動
  reboot:
    msg: "Rebooting the system to apply changes"
    connect_timeout: 5
    reboot_timeout: 600
  become: true

- name: GitLabからトークンを削除
  shell: >
    gitlab-rails runner "PersonalAccessToken.find_by_token('{{ gitlab_root_token }}').revoke!"
  become: yes

- name: GitLabからrootユーザーを削除
  shell: gitlab-rails runner "user = User.find_by_username('root'); user.destroy!"
  become: yes

- name: 不要なファイルを削除
  file:
    path: "{{ item }}"
    state: absent
  become: yes
  with_items:
    - /opt/gitlab/initial_configuration.sh
    - ~/gitlab.tar.gz
    - ~/gitlab

- name: user.txtを配置
  copy:
    src: user.txt
    dest: /home/m.yamada/user.txt
    owner: m.yamada
    group: m.yamada
    mode: '0644'
  become: true

- name: .bash_historyを/dev/nullにリダイレクト
  file:
    src: /dev/null
    dest: /home/m.yamada/.bash_history
    state: link
  become: true
