services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: postgres
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./init_msgs.sql:/docker-entrypoint-initdb.d/init_msgs.sql
      - ./admin.xml:/app/admin.xml
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8092:8092"
    volumes:
      - ./templates:/app/templates
    depends_on:
      - db
    environment:
      FLAG: flag{43s_f4s7_bu7_71m3_s10w3r}
    restart: always
