services:
  php-fpm:
    build:
      context: php
    depends_on:
      - db
    ports:
      - "8093:80"
    restart: always
  db:
    build:
      context: db
    environment:
      - MYSQL_DATABASE=cereal_blog
      - MYSQL_ROOT_PASSWORD=supersecret
    restart: always
