services:
  db:
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: 
      context: .
      dockerfile: Dockerfile.web
    restart: always
    env_file:
    - .env
    ports:
      - "8091:80"
    depends_on:
      - db
  victim:
    build: 
      context: .
      dockerfile: Dockerfile.victim
    restart: always
    env_file:
    - .env
    tty: true
    command: /bin/sh -c "cron -f"

volumes:
  db_data: