services:
  all_rust_and_no_safe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8109:8109"
    networks:
      - my_network
    restart: unless-stopped
    tty: true

networks:
  my_network:
    driver: bridge
